# Generated by Django 3.2.6 on 2023-04-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobspost',
            name='employment_status',
        ),
        migrations.AddField(
            model_name='jobspost',
            name='employment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.employmentstatus'),
        ),
    ]
