# Generated by Django 3.2.6 on 2023-04-04 04:49

import Core.models.profile
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Core.user')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Core.models.profile.media_upload_path, verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Spouse')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Father')),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Mother')),
                ('nid', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{10}|\\d{13}|\\d{17})$', message='Numeric 10/13/17 digits (ex: 1234567890)')], verbose_name='National ID')),
                ('passport', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{7}$', message='Alphanumeric 9 characters (ex: PA3456789)')], verbose_name='Passport')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address')),
                ('thana', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thana')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('division', models.CharField(blank=True, max_length=255, null=True, verbose_name='Division')),
                ('postal', models.CharField(blank=True, max_length=4, null=True, verbose_name='Postal Code')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('profile'), models.Model),
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Family Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0123456789)')], verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
