# Generated by Django 3.2.6 on 2023-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_category_jobspost_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobspost',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='Core.Category'),
        ),
        migrations.AlterField(
            model_name='jobspost',
            name='employment_status',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='Core.EmploymentStatus'),
        ),
        migrations.AlterField(
            model_name='jobspost',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='Core.Skill'),
        ),
    ]
