# Generated by Django 3.2.6 on 2023-03-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20230308_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobspost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
