# Generated by Django 3.2 on 2023-05-31 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_userskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('social_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.socialmedianame')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.profile')),
            ],
        ),
    ]
