# Generated by Django 3.2.6 on 2023-03-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_jobspost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images'),
        ),
    ]
