# Generated by Django 2.2.24 on 2022-04-02 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import site_settings.models.settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('domain', models.CharField(max_length=100, unique=True, validators=[site_settings.models.settings._simple_domain_name_validator], verbose_name='domain name')),
                ('name', models.CharField(max_length=255, verbose_name='display name')),
                ('logo', models.FileField(blank=True, help_text='Logo on the navbar', null=True, upload_to='logo/%Y/%m/%d/')),
                ('favicon', models.FileField(blank=True, help_text='Favicon on the meta title', null=True, upload_to='favicon/%Y/%m/%d/')),
                ('bg_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Background color')),
                ('text_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text color')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_sitesettings_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_sitesettings_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_sitesettings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
