# Generated by Django 3.2 on 2022-05-29 17:18

from django.db import migrations, models
import site_settings.models.settings


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20220407_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='domain',
            field=models.CharField(max_length=100, validators=[site_settings.models.settings._simple_domain_name_validator], verbose_name='domain name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='sitesettings',
            unique_together={('domain', 'is_active')},
        ),
    ]
